# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/02-stream.ipynb.

# %% auto #0
__all__ = ['get_image_from_ip_webcam', 'save_file_with_timestamp', 'get_image_from_camera']

# %% ../tutorials/02-stream.ipynb #3703b071
from IPython.display import display, Image
from typing import Union

# %% ../tutorials/02-stream.ipynb #5eb86a70
def get_image_from_ip_webcam(phone_ip, return_bytes: bool = False, debug_prn: bool = False) -> Union[bytes, Image]:
    import requests

    phone_url = f"http://{phone_ip}:8080/photo.jpg"

    if debug_prn:
        print(f"retrieving image from phone URL: {phone_url}")

    response = requests.get(phone_url, timeout=10)
    response.raise_for_status()

    if debug_prn:
        print(f"Retrieved {len(response.content)/1000} KB from phone camera.")

    if return_bytes:
        return response.content

    return Image(data=response.content)

# %% ../tutorials/02-stream.ipynb #71c03700
def save_file_with_timestamp(content, filename: str, output_folder: str, debug_prn: bool = False):
    """
    Save the image content to a file with a timestamp in the filename.

    Args:
        content (bytes): The image content to save.
        filename (str): The base filename to use for saving the image.
        output_folder (str): The folder where the image will be saved.
        debug_prn (bool): Whether to print debug information.
    """
    import datetime as dt

    # Get the current timestamp
    timestamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")

    # Create the full filename with timestamp
    full_filename = f"{output_folder}/{timestamp}_{filename}.jpg"

    # Save the image content to the file
    with open(full_filename, "wb") as f:
        f.write(content)

    if debug_prn:
        print(f"Saved image to {full_filename}")
    
    return full_filename

# %% ../tutorials/02-stream.ipynb #f0aa0bf0
def get_image_from_camera(
    camera_url: str,
    file_name = None,
    output_folder = None,
    debug_prn: bool = False
) -> str:
    """Grab one photo from the camera.

    Args:
        camera_url: where to ask for a photo. Usually `http://PHONE_IP:8080/photo.jpg`.
        timeout_seconds: how long to wait before giving up.
        file_name: the name to use for the saved file.
        output_folder: the folder where the image will be saved.

    Returns:
        Path to the saved JPEG or the image content as bytes if not saved.
    """

    content = get_image_from_ip_webcam(camera_url, return_bytes= True, debug_prn=debug_prn)

    if file_name and output_folder:
        file_path = save_file_with_timestamp(content=content, filename=file_name, output_folder=output_folder)
        if debug_prn:
            print(f"Saved image to {file_path}")
        return file_path
    else:
        if debug_prn:
            print(f"Retrieved {len(content)/1000} KB from camera.")
        return content


