# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/10-digest.ipynb.

# %% ../tutorials/10-digest.ipynb #98476167
# Lazy type-hint evaluation so `Path` doesn't need to be imported
# just to put it in a function signature.
from __future__ import annotations

# %% auto #0
__all__ = ['build_daily_summary', 'send_daily_summary', 'schedule_daily_summary']

# %% ../tutorials/10-digest.ipynb #ca54db48
from collections import Counter
from datetime import datetime, timedelta
from pathlib import Path
from .save_sighting import list_sightings_from_db

def build_daily_summary(
    db_file: Path,
    snapshot_folder: Path,
    window_hours: int = 24,
) -> dict:
    """Build a Slack message summarizing the last `window_hours` of sightings.

    Args:
        db_file: where sightings are stored.
        snapshot_folder: where snapshot images live (for referencing).
        window_hours: how far back to look. Default 24 (one day).

    Returns:
        A Slack Block Kit payload.
    """
    from collections import Counter
    from datetime import datetime, timedelta

    cutoff = (datetime.now() - timedelta(hours=window_hours)).isoformat(timespec="seconds")
    sightings = list_sightings_from_db(db_file, since=cutoff, limit=500, verbose=False)

    total = len(sightings)
    counts = Counter(s["species"] for s in sightings)
    unique_species = len(counts)
    top_visitor = counts.most_common(1)[0] if counts else None

    title = f":bird: Daily summary — {total} sighting(s), {unique_species} species"
    if top_visitor:
        title += f", top: *{top_visitor[0]}*"

    blocks: list[dict] = [
        {"type": "header", "text": {"type": "plain_text", "text": title}},
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*Window*\nlast {window_hours}h"},
                {"type": "mrkdwn", "text": f"*Total sightings*\n{total}"},
                {"type": "mrkdwn", "text": f"*Unique species*\n{unique_species}"},
            ],
        },
    ]
    if counts:
        species_lines = [
            f"• {species} — {count}" for species, count in counts.most_common(10)
        ]
        blocks.append(
            {
                "type": "section",
                "text": {"type": "mrkdwn", "text": "*Top species*\n" + "\n".join(species_lines)},
            }
        )

    return {"blocks": blocks}


# %% ../tutorials/10-digest.ipynb #6867d4c9
from pathlib import Path
from .send_alert import send_alert_to_slack

def send_daily_summary(
    db_file: Path,
    snapshot_folder: Path,
    window_hours: int = 24,
    webhook_url: str | None = None,
    verbose: bool = True,
) -> bool:
    """Build and send (or dry-run) today's daily summary.

    Args:
        db_file: where sightings are stored.
        snapshot_folder: where snapshot images live.
        window_hours: how far back to look.
        webhook_url: optional Slack webhook URL. If omitted, this becomes a dry run.
        verbose: if True, print a status line.

    Returns:
        True if sent (or dry-run previewed), False on error.
    """
    from bird_watcher.send_alert import send_alert_to_slack

    payload = build_daily_summary(db_file, snapshot_folder, window_hours=window_hours)
    return send_alert_to_slack(payload, webhook_url=webhook_url, verbose=verbose)


# %% ../tutorials/10-digest.ipynb #29caa987
import time
from pathlib import Path
import schedule

def schedule_daily_summary(
    db_file: Path,
    snapshot_folder: Path,
    run_at_hour: int = 21,
    verbose: bool = True,
) -> None:
    """Run a blocking scheduler that posts the daily summary once a day.

    For learning purposes only — production code would use a real cron job.

    Args:
        db_file: where sightings are stored.
        snapshot_folder: where snapshot images live.
        run_at_hour: hour of day to send (24h format). Default 21 (9pm).
        verbose: if True, print the next scheduled run.
    """
    import time

    import schedule

    job = lambda: send_daily_summary(db_file, snapshot_folder, verbose=verbose)
    schedule.every().day.at(f"{run_at_hour:02d}:00").do(job)
    if verbose:
        print(f"Scheduled daily summary at {run_at_hour:02d}:00 every day")
        print("Press Stop / Ctrl+C to exit")
    while True:
        schedule.run_pending()
        time.sleep(60)

