# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/04-detect.ipynb.

# %% auto #0
__all__ = ['YoloModelEnum', 'ImageDetected', 'detect_objects_in_image', 'ImageDetection']

# %% ../tutorials/04-detect.ipynb #208179a3
from enum import Enum
from ultralytics import YOLO
from dataclasses import dataclass

from PIL import Image as PILImage, ImageDraw



# %% ../tutorials/04-detect.ipynb #e55b9aa3
class YoloModelEnum(Enum):
    QUALITY = 'yolo26l.pt'
    FAST = 'yolo26n.pt'

# %% ../tutorials/04-detect.ipynb #48a8a83a
@dataclass
class ImageDetected:
    img_path: str
    detection_box : tuple[int, int, int, int]
    label_id: int # YOLO class index
    label: str # YOLO class name

    def __post_init__(self):
        pass

    
    @property
    def print_boundaries(self) -> None:
        x_min, y_min, x_max, y_max = self.detection_box
        return f"  {self.label} ({self.label_id}): ({int(x_min)}, {int(y_min)}) - ({int(x_max)}, {int(y_max)})"

    @property
    def print_cropped_image(self) -> "Image.Image":
        from PIL import Image
        image = Image.open(self.img_path)
        x_min, y_min, x_max, y_max = self.detection_box
        return image.crop((x_min, y_min, x_max, y_max))
    
    @property
    def print_cropped_bytes(self) -> bytes:
        from PIL import Image
        from io import BytesIO
        image = Image.open(self.img_path)
        x_min, y_min, x_max, y_max = self.detection_box
        cropped_image = image.crop((x_min, y_min, x_max, y_max))
        
        # Save the cropped image to a bytes buffer
        buffer = BytesIO()
        cropped_image.save(buffer, format="JPEG")
        return buffer.getvalue()

    
def detect_objects_in_image(img_path, model: YOLO, confidence: float = 0.7, debug_prn: bool = False) -> list[ImageDetected]:

    results = model(str(img_path), conf=confidence, verbose=False)

    detected_objects  = []

    for result in results:
        for detection in result.boxes:
            image_detect = ImageDetected(
                img_path=img_path,
                detection_box=tuple(detection.xyxy[0].tolist()),
                label_id=int(detection.cls[0]),
                label=model.names[int(detection.cls[0])]
            )
            detected_objects.append(image_detect)
            
            if debug_prn:
                image_detect.show_detection(debug_prn=True)
            
    return detected_objects


# %% ../tutorials/04-detect.ipynb #c9573b10
@dataclass
class ImageDetection:
    imag_path : str
    model : YOLO
    detections: list[ImageDetected] = None

    @property
    def image(self) -> PILImage.Image:
        
        return PILImage.open(self.imag_path).convert("RGB")

    
    @classmethod
    def from_path(cls, img_path: str,model: YOLO,  confidence: float = 0.7, debug_prn : bool = False) -> "ImageDetection":
        
        img =  cls(imag_path=img_path, model=model)

        img.get_detections(model=model, confidence=confidence, debug_prn=debug_prn)

        return img
    
    
    def get_detections(self, model: YOLO, confidence: float = 0.7, debug_prn: bool = False) -> list[ImageDetected]:
        
        self.detections = detect_objects_in_image(img_path = self.imag_path, model=model, confidence=confidence, debug_prn=debug_prn)
        
        return self.detections

    @property
    def print_detections(self) -> PILImage.Image:
        annotated = PILImage.open(self.imag_path).convert("RGB").copy()
        draw = ImageDraw.Draw(annotated)

        for detection in self.detections:
            x_min, y_min, x_max, y_max = detection.detection_box
            draw.rectangle([x_min, y_min, x_max, y_max], outline="red", width=2)
            draw.text((x_min, y_min), detection.label, fill="red")
        

        return annotated
