# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/01-setup.ipynb.

# %% auto #0
__all__ = ['load_config', 'load_environment']

# %% ../tutorials/01-setup.ipynb #7902699c
from pathlib import Path
from dotenv import load_dotenv
import os
import yaml


# %% ../tutorials/01-setup.ipynb #66333713
def load_config(config_path: str = '../config.yaml', debug_prn: bool = False):
    """Load configuration from a YAML file."""

    config_file = Path(config_path)

    if not config_file.exists():
        raise FileNotFoundError(f"Configuration file {config_path} not found.")
    
    if debug_prn:
        print(f'loading config {config_file }')

    with open(config_file, "r") as f:
        config = yaml.safe_load(f)
    
    return config

def load_environment(env_path: str = '../.env', debug_prn: bool = False):
    """Load environment variables from a .env file."""

    if not load_dotenv(env_path):
        raise RuntimeError(f"Failed to load .env file at {env_path}. Make sure it exists and contains HUGGINGFACE_API_KEY.")

    if debug_prn:
        print(f'loading environment variables from {env_path}')
    
    hf_token = os.environ.get("HUGGINGFACE_API_KEY")
    if not hf_token:
        raise RuntimeError("HUGGINGFACE_API_KEY is not set in the environment variables.")
    
    phone_ip = os.environ.get("PHONE_IP")
    if not phone_ip:
        raise RuntimeError("PHONE_IP is not set in the environment variables.")
    
    PHONE_URL = f"http://{phone_ip}:8080/photo.jpg"

    return 1

