# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/04-detect.ipynb.

# %% auto #0
__all__ = ['find_birds_in_image', 'crop_bird_from_image']

# %% ../tutorials/04-detect.ipynb #359479c2
from pathlib import Path
from ultralytics import YOLO

def find_birds_in_image(
    frame_file: Path,
    model_file: Path,
    confidence_threshold: float = 0.4,
    verbose: bool = True,
) -> list[dict]:
    """Find every bird in a single photo.

    Args:
        frame_file: path to the JPEG to analyze.
        model_file: path to the YOLO model weights (e.g. yolov8n.pt).
        confidence_threshold: ignore detections weaker than this (0.0 - 1.0).
        verbose: if True, print how many birds were found. Default True.

    Returns:
        A list of bounding boxes. Each box is a dict:
            {
                "x_min": int, "y_min": int, "x_max": int, "y_max": int,
                "confidence": float,
            }
        Empty list means no birds found.
    """
    from ultralytics import YOLO

    model = YOLO(str(model_file))
    results = model(str(frame_file), conf=confidence_threshold, verbose=False)

    boxes: list[dict] = []
    for result in results:
        for detection in result.boxes:
            class_id = int(detection.cls[0])
            class_name = model.names[class_id]
            if class_name != "bird":
                continue
            x_min, y_min, x_max, y_max = detection.xyxy[0].tolist()
            boxes.append(
                {
                    "x_min": int(x_min),
                    "y_min": int(y_min),
                    "x_max": int(x_max),
                    "y_max": int(y_max),
                    "confidence": float(detection.conf[0]),
                }
            )

    if verbose:
        print(f"Found {len(boxes)} bird(s) in {frame_file.name}")
    return boxes


# %% ../tutorials/04-detect.ipynb #317d6b0a
from pathlib import Path
from PIL import Image

def crop_bird_from_image(
    frame_file: Path,
    bounding_box: dict,
    crop_folder: str,
    verbose: bool = True,
) -> Path:
    """Cut out a single bird from a photo using a bounding box.

    Args:
        frame_file: the source photo.
        bounding_box: dict with x_min, y_min, x_max, y_max.
        crop_folder: where to save the cropped image. Created if missing.
        verbose: if True, print where the crop was saved. Default True.

    Returns:
        Path to the cropped JPEG.
    """
    from PIL import Image

    folder = Path(crop_folder)
    folder.mkdir(parents=True, exist_ok=True)

    image = Image.open(frame_file)
    crop_box = (
        bounding_box["x_min"],
        bounding_box["y_min"],
        bounding_box["x_max"],
        bounding_box["y_max"],
    )
    cropped = image.crop(crop_box)

    crop_file = folder / f"{frame_file.stem}-crop.jpg"
    cropped.save(crop_file, "JPEG")
    if verbose:
        print(f"Saved crop: {crop_file}")
    return crop_file

