# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/02-stream.ipynb.

# %% auto #0
__all__ = ['get_image_from_camera', 'get_images_from_camera']

# %% ../tutorials/02-stream.ipynb #f0aa0bf0
from datetime import datetime
from pathlib import Path
import requests

def get_image_from_camera(
    camera_url: str,
    snapshot_folder: str,
    timeout_seconds: float = 10.0,
) -> Path:
    """Grab one photo from the camera and save it with a timestamp filename.

    Args:
        camera_url: where to ask for a photo. Usually `http://PHONE_IP:8080/photo.jpg`.
        snapshot_folder: which folder to write the photo into. Created if missing.
        timeout_seconds: how long to wait before giving up.

    Returns:
        Path to the saved JPEG.
    """
    folder = Path(snapshot_folder)
    folder.mkdir(parents=True, exist_ok=True)

    response = requests.get(camera_url, timeout=timeout_seconds)
    response.raise_for_status()

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    snapshot_file = folder / f"{timestamp}.jpg"
    snapshot_file.write_bytes(response.content)
    return snapshot_file


# %% ../tutorials/02-stream.ipynb #5179d763
import time
from pathlib import Path

def get_images_from_camera(
    camera_url: str,
    snapshot_folder: str,
    num_frames: int,
    wait_seconds: float,
    verbose: bool = True,
) -> list[Path]:
    """Grab several photos from the camera, one every `wait_seconds`.

    Each photo gets its own timestamped filename. Stops early if the user
    presses Stop (KeyboardInterrupt).

    Args:
        camera_url: where to ask for a photo.
        snapshot_folder: which folder to write the photos into.
        num_frames: how many photos to grab before stopping.
        wait_seconds: how long to pause between photos.
        verbose: if True, print each saved photo's name. Default True.

    Returns:
        List of paths to the saved JPEGs, in the order they were taken.
    """
    import time

    saved_files: list[Path] = []
    try:
        for index in range(num_frames):
            snapshot_file = get_image_from_camera(camera_url, snapshot_folder)
            saved_files.append(snapshot_file)
            if verbose:
                print(f"[{index + 1}/{num_frames}] saved {snapshot_file.name}")
            if index < num_frames - 1:
                time.sleep(wait_seconds)
    except KeyboardInterrupt:
        if verbose:
            print("Stopped by user")
    return saved_files

