# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/05-identify.ipynb.

# %% auto #0
__all__ = ['name_bird_in_image']

# %% ../tutorials/05-identify.ipynb #a958e5a1
from pathlib import Path
from transformers import pipeline

def name_bird_in_image(
    crop_file: Path,
    top_k: int = 3,
    verbose: bool = True,
) -> list[dict]:
    """Guess the species of the bird in a cropped photo.

    Args:
        crop_file: a JPEG containing mostly one bird.
        top_k: how many guesses to return, ranked by confidence.
        verbose: if True, print the top guess. Default True.

    Returns:
        A list of guesses. Each is a dict:
            {"species": str, "confidence": float}
        Sorted from most to least confident.
    """
    from transformers import pipeline

    classifier = pipeline(
        task="image-classification",
        model="dennisjooo/Birds-Classifier",
    )
    guesses = classifier(str(crop_file), top_k=top_k)

    results = [
        {"species": guess["label"], "confidence": float(guess["score"])}
        for guess in guesses
    ]

    if verbose and results:
        top = results[0]
        print(f"Top guess: {top['species']} ({top['confidence']:.2f})")
    return results

