# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/06-persist.ipynb.

# %% auto #0
__all__ = ['save_sighting_to_db', 'list_sightings_from_db']

# %% ../tutorials/06-persist.ipynb #5c862ab8
import sqlite3
from datetime import datetime
from pathlib import Path

def save_sighting_to_db(
    db_file: Path,
    snapshot_file: Path,
    species: str,
    confidence: float,
    bounding_box: dict | None = None,
    verbose: bool = True,
) -> int:
    """Add one new sighting to the database.

    Args:
        db_file: path to the SQLite file.
        snapshot_file: path to the photo file this sighting came from.
        species: the bird's name.
        confidence: how sure the classifier was, 0.0 - 1.0.
        bounding_box: optional dict with x_min, y_min, x_max, y_max.
        verbose: if True, print the new row id. Default True.

    Returns:
        The new row's id (auto-incremented).
    """
    import sqlite3
    from datetime import datetime

    db_file.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().isoformat(timespec="seconds")
    with sqlite3.connect(db_file) as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sightings (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                timestamp       TEXT    NOT NULL,
                species         TEXT    NOT NULL,
                confidence      REAL    NOT NULL,
                snapshot_file   TEXT    NOT NULL,
                bbox_x_min      INTEGER,
                bbox_y_min      INTEGER,
                bbox_x_max      INTEGER,
                bbox_y_max      INTEGER
            )
            """
        )
        cursor = conn.execute(
            """
            INSERT INTO sightings (
                timestamp, species, confidence, snapshot_file,
                bbox_x_min, bbox_y_min, bbox_x_max, bbox_y_max
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                timestamp,
                species,
                confidence,
                str(snapshot_file),
                bounding_box.get("x_min") if bounding_box else None,
                bounding_box.get("y_min") if bounding_box else None,
                bounding_box.get("x_max") if bounding_box else None,
                bounding_box.get("y_max") if bounding_box else None,
            ),
        )
        conn.commit()
        row_id = cursor.lastrowid
    if verbose:
        print(f"Saved sighting #{row_id}: {species} ({confidence:.2f})")
    return row_id


# %% ../tutorials/06-persist.ipynb #699cf358
import sqlite3
from pathlib import Path

def list_sightings_from_db(
    db_file: Path,
    since: str | None = None,
    limit: int = 100,
    verbose: bool = True,
) -> list[dict]:
    """Get sightings from the database, most recent first.

    Args:
        db_file: path to the SQLite file.
        since: optional ISO timestamp; only return sightings after this.
        limit: max rows to return.
        verbose: if True, print a count. Default True.

    Returns:
        List of sighting dicts, sorted by timestamp descending.
    """
    import sqlite3

    if not db_file.exists():
        return []
    with sqlite3.connect(db_file) as conn:
        conn.row_factory = sqlite3.Row
        if since:
            cursor = conn.execute(
                """
                SELECT * FROM sightings
                WHERE timestamp >= ?
                ORDER BY timestamp DESC
                LIMIT ?
                """,
                (since, limit),
            )
        else:
            cursor = conn.execute(
                "SELECT * FROM sightings ORDER BY timestamp DESC LIMIT ?",
                (limit,),
            )
        rows = [dict(row) for row in cursor.fetchall()]
    if verbose:
        print(f"{len(rows)} sighting(s) in {db_file.name}")
    return rows

