# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/05-identify.ipynb.

# %% auto #0
__all__ = ['SpeciesGuess', 'ImageClassifier', 'BirdClassifier', 'DogClassifier', 'ImageClassifierEnum']

# %% ../tutorials/05-identify.ipynb #049a10af
import numpy as np
from pathlib import Path
from dataclasses import dataclass
from IPython.display import Image
from typing import List



# %% ../tutorials/05-identify.ipynb #2c175c5d
@dataclass
class SpeciesGuess:
    species: str
    confidence: float

    def print(self): # the standardized output
        return f"Species: {self.species}, Confidence: {self.confidence:.2f}"

@dataclass
class ImageClassifier:
    img : Image
    guesses : List[SpeciesGuess] = None

    @property
    def species(self):
        if self.guesses is None or len(self.guesses) == 0:
            self.classify()
        return self.guesses[0].species
    
    @property
    def confidence(self):
        if self.guesses is None or len(self.guesses) == 0:
            self.classify()
        return self.guesses[0].confidence

    @property
    def print(self):
        if self.guesses is None or len(self.guesses) == 0:
            self.classify()

        if not self.guesses:
            raise ValueError("No guesses available. The classify method did not return any results.")

        return f"This is a {self.guesses[0].species} with a confidence of {self.guesses[0].confidence:.2f}"
    
    def __post_init__(self):
        self.classify()

        
    def classify(self):
        raise NotImplementedError("Subclasses should implement this method.")

# %% ../tutorials/05-identify.ipynb #9dc77706
@dataclass
class BirdClassifier(ImageClassifier):
    
    def classify(self, debug_prn: bool = False):

        results = bird_classifier(self.img, top_k=3)
        
        guesses = [SpeciesGuess(species=res['label'], confidence=res['score']) for res in results]

        if debug_prn:
            for guess in guesses:
                print(guess.print())
            
        self.guesses = guesses
        return guesses[0]

# %% ../tutorials/05-identify.ipynb #d36d82ca
@dataclass
class DogClassifier(ImageClassifier):
    """Predict dog breed probabilities for a cropped dog image.

    Args:
        img: a PIL image containing one dog.
        top_k: how many predictions to return.
        verbose: if True, print the top predictions.

    Returns:
        A list of predictions sorted by confidence.
    """

    def classify(self, top_k: int = 3, debug_prn: bool = False):

        resized_img = self.img.convert("RGB").resize((224, 224))
        img_array = tf.keras.utils.img_to_array(resized_img) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        predictions = dog_model.predict(img_array, verbose=0)[0]
        top_indices = np.argsort(predictions)[::-1][:top_k]

        self.guesses = [SpeciesGuess(species=dog_class_names[index], confidence=float(predictions[index])) for index in top_indices]

        if debug_prn:
            for guess in self.guesses:
                print(guess.print())
        
        return self.guesses[0]



# %% ../tutorials/05-identify.ipynb #4d521bb0
from enum import Enum
from fastcore.basics import patch_to
from .detect import ImageDetected, ImageDetection

class ImageClassifierEnum(Enum):
    BIRD = BirdClassifier
    DOG = DogClassifier


@patch_to(ImageDetected)
def __post_init__(self):
    classifier_enum = ImageClassifierEnum.__members__.get(self.label.upper())
    if classifier_enum is None:
        self.Classifier = None
        return
    self.Classifier = classifier_enum.value(self.print_cropped_image)
