# AUTOGENERATED! DO NOT EDIT! File to edit: ../tutorials/09-gallery.ipynb.

# %% ../tutorials/09-gallery.ipynb #98554958
# Lazy type-hint evaluation so `Path` doesn't need to be imported
# just to put it in a function signature.
from __future__ import annotations

# %% auto #0
__all__ = ['create_app']

# %% ../tutorials/09-gallery.ipynb #914ec2e1
from pathlib import Path
from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from .save_sighting import list_sightings_from_db

def create_app(
    db_file: Path,
    snapshot_folder: Path,
) -> FastAPI:
    """Build the full Bird Watcher FastAPI app.

    Endpoints:
        GET /          — landing page metadata
        GET /health    — uptime check
        GET /gallery   — recent sightings as JSON
        GET /snapshots/... — static thumbnails (mounted if folder exists)

    Args:
        db_file: path to the SQLite file with sightings.
        snapshot_folder: folder of saved JPEG snapshots (mounted for thumbnails).

    Returns:
        A configured FastAPI app, ready to be served with uvicorn.
    """
    from fastapi import FastAPI
    from fastapi.staticfiles import StaticFiles

    from bird_watcher.save_sighting import list_sightings_from_db

    app = FastAPI(title="Bird Watcher", version="0.0.0")

    @app.get("/")
    def index() -> dict:
        """Landing page."""
        return {"app": "bird-watcher", "status": "watching"}

    @app.get("/health")
    def health() -> dict:
        """Health check — useful for uptime monitoring."""
        return {"status": "ok"}

    @app.get("/gallery")
    def gallery(limit: int = 50) -> dict:
        """Recent sightings with thumbnails."""
        rows = list_sightings_from_db(db_file, limit=limit, verbose=False)
        return {"count": len(rows), "sightings": rows}

    if snapshot_folder.exists():
        app.mount(
            "/snapshots",
            StaticFiles(directory=str(snapshot_folder)),
            name="snapshots",
        )

    return app

